name: Deploy Flutter Web App

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'  # Use the stable channel which should include Dart >= 3.1.0

    - name: Check Flutter version
      run: flutter --version

    - name: Check Dart version
      run: dart --version

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
