name: Deploy Flutter Web App

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Flutter
      run: |
        sudo apt-get update
        sudo apt-get install -y curl unzip xz-utils git
        curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.3.2-stable.tar.xz
        tar xf flutter_linux_3.3.2-stable.tar.xz
        export PATH="$PATH:`pwd`/flutter/bin"
        flutter doctor

    - name: Check Flutter and Dart version
      run: flutter --version

    - name: Check Dart version
      run: dart --version

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/web
